# -*- coding: utf-8 -*-
"""Student WorkGroup Report Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-n5kQD1z0143CFLsRu6kqEWp-A7grnpl
"""

import streamlit as st
import requests
import pandas as pd
import io
from datetime import datetime, timedelta

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Student Report Generator", page_icon="📊")

st.title("📊 Kidum Student Reports")
st.write("Enter your credentials to download the latest student work group data.")

# --- 1. SESSION STATE SETUP (Keeps you logged in) ---
if 'auth_token' not in st.session_state:
    st.session_state.auth_token = None

# --- 2. SIDEBAR: LOGIN ---
with st.sidebar:
    st.header("🔐 Login")
    email = st.text_input("Email")
    password = st.text_input("Password", type="password")

    if st.button("Log In"):
        login_url = "https://lmsapi.kidum-me.com/api/login"
        payload = {"email": email, "password": password}
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0"
        }

        try:
            with st.spinner("Logging in..."):
                response = requests.post(login_url, json=payload, headers=headers)
                response.raise_for_status()
                data = response.json()
                token = data.get("token") or data.get("access_token")

                if token:
                    st.session_state.auth_token = token
                    st.success("Login Successful!")
                else:
                    st.error("Login failed: No token received.")
        except Exception as e:
            st.error(f"Login Error: {e}")

# --- 3. MAIN APP LOGIC ---
if st.session_state.auth_token:
    st.divider()
    st.subheader("📥 Generate Report")

    # Fetch Data Button
    if st.button("Load Data from Server"):
        export_url = "https://lmsapi.kidum-me.com/api/export-student-work-group-details"
        export_headers = {
            "Authorization": f"Bearer {st.session_state.auth_token}",
            "User-Agent": "Mozilla/5.0",
            "Referer": "https://lmsadmin.kidum-me.com/",
            "Origin": "https://lmsadmin.kidum-me.com"
        }

        try:
            with st.spinner("Fetching data..."):
                r = requests.get(export_url, headers=export_headers)
                r.raise_for_status()

                # Check format
                content_type = r.headers.get('Content-Type', '')
                if 'excel' in content_type or 'spreadsheet' in content_type:
                    df = pd.read_excel(io.BytesIO(r.content))
                else:
                    df = pd.DataFrame(r.json())

                # Clean Data
                df.columns = df.columns.str.strip()
                df['meeting_date'] = pd.to_datetime(df['meeting_date'], errors='coerce')

                # Save to session state so we don't have to reload
                st.session_state.df = df
                st.success(f"Data Loaded: {len(df)} rows found.")
        except Exception as e:
            st.error(f"Error fetching data: {e}")

    # --- 4. FILTERING & DOWNLOAD ---
    if 'df' in st.session_state:
        df = st.session_state.df

        # Date Logic
        today = datetime.now().date()
        idx = (today.weekday() + 1) % 7
        sun_start = today - timedelta(idx)
        sat_end = sun_start + timedelta(days=6)

        st.info(f"📅 Current Week Scope: **{sun_start}** to **{sat_end}**")

        # User Choice
        report_type = st.radio(
            "Select Report Type:",
            ("All Data", "Current Week", "Specific Group (Week)", "Summary (Count)")
        )

        final_df = df.copy()
        file_prefix = "report"

        # Apply Logic
        if report_type == "Current Week":
            file_prefix = "weekly_report"
            final_df = final_df[
                (final_df['meeting_date'].dt.date >= sun_start) &
                (final_df['meeting_date'].dt.date <= sat_end)
            ]

        elif report_type == "Specific Group (Week)":
            # Filter by week first
            final_df = final_df[
                (final_df['meeting_date'].dt.date >= sun_start) &
                (final_df['meeting_date'].dt.date <= sat_end)
            ]
            # Group selector
            available_groups = final_df['group_name'].unique()
            target_group = st.selectbox("Select Group:", available_groups)

            if target_group:
                final_df = final_df[final_df['group_name'] == target_group]
                file_prefix = f"group_{target_group}_week"

        elif report_type == "Summary (Count)":
            file_prefix = "weekly_summary"
            weekly_data = final_df[
                (final_df['meeting_date'].dt.date >= sun_start) &
                (final_df['meeting_date'].dt.date <= sat_end)
            ]

            # Handle Hour column
            if 'hour' not in weekly_data.columns:
                 found = [c for c in weekly_data.columns if 'hour' in c.lower().strip()]
                 if found: weekly_data = weekly_data.rename(columns={found[0]: 'hour'})

            # Group by
            try:
                final_df = weekly_data.groupby(['group_name', 'hour'])['student_id'].nunique().reset_index()
                final_df.columns = ['Group Name', 'Hour', 'Unique Student Count']
                final_df = final_df.sort_values(by=['Group Name', 'Hour'])
            except KeyError:
                st.error("Could not find 'group_name' or 'hour' columns.")
                final_df = pd.DataFrame()

        # Preview
        st.write("### Preview")
        st.dataframe(final_df.head())

        # Download Button
        if not final_df.empty:
            # Convert DF to Excel in memory
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
                final_df.to_excel(writer, index=False)
            processed_data = output.getvalue()

            timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            st.download_button(
                label=f"⬇️ Download {file_prefix}.xlsx",
                data=processed_data,
                file_name=f"{file_prefix}_{timestamp}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
else:
    st.info("Please log in from the sidebar to continue.")
